// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuM2Mv3YlLRVUXjzFgeHuK1JBuAglbzm0',
    appId: '1:15395032481:web:7a56ea1d115f6843014fe0',
    messagingSenderId: '15395032481',
    projectId: 'mau-hien-production',
    authDomain: 'mau-hien-production.firebaseapp.com',
    storageBucket: 'mau-hien-production.firebasestorage.app',
    measurementId: 'G-HTTTHZC0EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuM2Mv3YlLRVUXjzFgeHuK1JBuAglbzm0',
    appId: '1:15395032481:web:7a56ea1d115f6843014fe0',
    messagingSenderId: '15395032481',
    projectId: 'mau-hien-production',
    storageBucket: 'mau-hien-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuM2Mv3YlLRVUXjzFgeHuK1JBuAglbzm0',
    appId: '1:15395032481:web:7a56ea1d115f6843014fe0',
    messagingSenderId: '15395032481',
    projectId: 'mau-hien-production',
    storageBucket: 'mau-hien-production.firebasestorage.app',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'com.example.vietPosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuM2Mv3YlLRVUXjzFgeHuK1JBuAglbzm0',
    appId: '1:15395032481:web:7a56ea1d115f6843014fe0',
    messagingSenderId: '15395032481',
    projectId: 'mau-hien-production',
    storageBucket: 'mau-hien-production.firebasestorage.app',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'com.example.vietPosFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1gxPqELZZYiC86M3Bqz506X7TRYjeJSQ',
    appId: '1:588886544003:web:29ce1c87f0b5e2f3c2d5b6',
    messagingSenderId: '588886544003',
    projectId: 'viet-pos-db',
    authDomain: 'viet-pos-db.firebaseapp.com',
    storageBucket: 'viet-pos-db.firebasestorage.app',
    measurementId: 'G-GPRTJH7TGS',
  );

}