// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC8uly3qG-uZNf4ujzomkDAs_TXmDc2CBg",
      authDomain: "vet-pos-prod.firebaseapp.com",
      projectId: "vet-pos-prod",
      storageBucket: "vet-pos-prod.firebasestorage.app",
      messagingSenderId: "342929701524",
      appId: "1:342929701524:web:5ed16e5f878c9f17c55281",
      measurementId: "G-WTQVL7HQBZ"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6kGOk-_mWaWvURcQVwc0EX68rf620FA',
    appId: '1:588886544003:android:1aa178490a76156cc2d5b6',
    messagingSenderId: '588886544003',
    projectId: 'viet-pos-db',
    storageBucket: 'viet-pos-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxUrsSeuIzmkL4UogGK6Z0TG269IeQSA',
    appId: '1:588886544003:ios:c503457f261824d3c2d5b6',
    messagingSenderId: '588886544003',
    projectId: 'viet-pos-db',
    storageBucket: 'viet-pos-db.firebasestorage.app',
    iosBundleId: 'com.example.vietPosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxUrsSeuIzmkL4UogGK6Z0TG269IeQSA',
    appId: '1:588886544003:ios:c503457f261824d3c2d5b6',
    messagingSenderId: '588886544003',
    projectId: 'viet-pos-db',
    storageBucket: 'viet-pos-db.firebasestorage.app',
    iosBundleId: 'com.example.vietPosFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
     apiKey: "AIzaSyC8uly3qG-uZNf4ujzomkDAs_TXmDc2CBg",
  authDomain: "vet-pos-prod.firebaseapp.com",
  projectId: "vet-pos-prod",
  storageBucket: "vet-pos-prod.firebasestorage.app",
  messagingSenderId: "342929701524",
  appId: "1:342929701524:web:5ed16e5f878c9f17c55281",
  measurementId: "G-WTQVL7HQBZ" 
  );

}